name: Working Dir and Shells
on: [push]
jobs: 
    display-working-dir-info:
        runs-on: ubuntu-latest
        steps:
            - name: Display Working Directory & List Files
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
                
    display-working-dir-info-windows:
        runs-on: windows-latest
        steps:
            - name: Display Working Directory & List Files
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
                            

                